name: CI

on:
  pull_request:
  push:
    branches: [ '*' ]
    branches-ignore:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.3'  # 使用するRubyのバージョンを指定

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run Brakeman
        run: bin/brakeman

      - name: Run RuboCop
        run: bin/rubocop

      - name: Run RSpec
        run: bundle exec rspec